<?php

namespace Database\Seeders;

use App\Models\Berita;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class BeritaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Berita::create([
            'judul' => 'MUSDES DESA ADAT TAHUNAN TAHUN 2023',
            'slug' => 'musdes-desa-adat-tahunan-tahun-2023',
            'konten' => "<p class='MsoNormal' style='text-align: justify; text-justify: inter-ideograph;'><span style='font-size: 12.0pt; font-family: 'Times New Roman',serif; mso-bidi-theme-font: minor-bidi;'>Musyawarah desa di Desa Suka Maju menjadi platform penting dalam memajukan dan mengembangkan komunitas tersebut. Dalam musyawarah ini, warga desa Suka Maju secara aktif terlibat dalam pengambilan keputusan yang berdampak pada perkembangan desa mereka. Masyarakat desa memiliki kesempatan untuk berbagi gagasan, pemikiran, dan aspirasi mereka, sehingga menciptakan iklim partisipatif yang kuat di dalam komunitas.</span></p>
            <p class='MsoNormal' style='text-align: justify; text-justify: inter-ideograph;'><span style='font-size: 12.0pt; font-family: 'Times New Roman',serif; mso-bidi-theme-font: minor-bidi;'>Salah satu keuntungan dari musyawarah desa di Desa Suka Maju adalah terciptanya kesepakatan yang lebih inklusif dan adil. Dalam proses musyawarah ini, semua suara dianggap sama pentingnya, tidak ada seorang pun yang diabaikan. Keputusan yang diambil didasarkan pada konsensus dan kesepakatan bersama, sehingga memberikan rasa memiliki dan tanggung jawab yang lebih besar kepada seluruh warga desa terhadap perkembangan dan kemajuan desa mereka.</span></p>
            <p class='MsoNormal' style='text-align: justify; text-justify: inter-ideograph;'><span style='font-size: 12.0pt; font-family: 'Times New Roman',serif; mso-bidi-theme-font: minor-bidi;'>Selain itu, musyawarah desa di Desa Suka Maju juga menjadi sarana untuk membangun kebersamaan dan solidaritas di antara warga desa. Melalui proses musyawarah yang terbuka dan transparan, warga desa memiliki kesempatan untuk saling berbagi informasi, pemikiran, dan ide-ide kreatif. Hal ini tidak hanya memperkuat ikatan sosial antara mereka, tetapi juga memungkinkan terciptanya solusi yang lebih baik dan inovatif dalam mengatasi masalah-masalah yang dihadapi oleh desa tersebut.</span></p>",
            'excerpt' => 'Musyawarah desa di Desa Suka Maju menjadi platform penting dalam memajukan dan mengembangkan komunitas tersebut. Dalam musyawarah ini, warga desa Suka Maju secara aktif terlibat dalam pengambilan kepu...',
            'gambar' => '2981f_gambar5.jpg',
            'tanggal_upload' => '2023-06-06 23:46:42',
        ]);

        Berita::create([
            'judul' => 'RAPAT PLENO TERBUKA TERKAIT PEMILU',
            'slug' => 'rapat-pleno-terbuka-terkait-pemilu',
            'konten' => '<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph;"><span style="font-size: 12.0pt; font-family: "Times New Roman",serif; mso-bidi-theme-font: minor-bidi;">Rapat pleno terbuka terkait pemilu di Desa Suka Maju merupakan momen penting dalam proses demokrasi yang melibatkan seluruh warga desa. Rapat pleno ini diadakan untuk membahas persiapan dan pelaksanaan pemilihan umum di tingkat desa. Dalam rapat ini, warga desa berhak untuk memberikan masukan, memberikan pendapat, dan ikut serta dalam pengambilan keputusan terkait pemilu, sehingga tercipta transparansi dan akuntabilitas dalam proses demokrasi.</span></p>
            <p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph;"><span style="font-size: 12.0pt; font-family: "Times New Roman",serif; mso-bidi-theme-font: minor-bidi;">Melalui rapat pleno terbuka terkait pemilu di Desa Suka Maju, masyarakat desa memiliki kesempatan untuk mendiskusikan masalah-masalah terkait pemilihan umum, seperti penyusunan daftar pemilih, pemilihan calon kepala desa, serta proses kampanye dan pemungutan suara. Rapat ini menjadi sarana untuk memberikan pemahaman yang lebih baik kepada warga desa tentang proses pemilu dan pentingnya partisipasi aktif dalam menentukan masa depan desa.</span></p>
            <p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph;"><span style="font-size: 12.0pt; font-family: "Times New Roman",serif; mso-bidi-theme-font: minor-bidi;">Selain itu, rapat pleno terbuka juga menjadi kesempatan bagi warga desa untuk memberikan masukan terhadap penyelenggaraan pemilu yang lebih baik. Dalam rapat ini, masyarakat desa dapat menyampaikan saran, kritik, dan aspirasi mereka terkait dengan proses pemilu yang sedang berlangsung. Hal ini memberikan ruang bagi perbaikan dan peningkatan dalam penyelenggaraan pemilu, sehingga tercipta pemilihan yang adil, demokratis, dan berkualitas di Desa Suka Maju.</span></p>',
            'excerpt' => 'Rapat pleno terbuka terkait pemilu di Desa Suka Maju merupakan momen penting dalam proses demokrasi yang melibatkan seluruh warga desa. Rapat pleno ini diadakan untuk membahas persiapan dan pelaksanaa...',
            'gambar' => '2c62e_contohgambar.jpeg',
            'tanggal_upload' => '2023-06-03 23:46:42',
        ]);

        Berita::create([
            'judul' => 'SOSIALISASI PEMBENTUKAN DAN PEMBINAAN DESA SADAR HUKUM',
            'slug' => 'sosialisasi-pembentukan-dan-pembinaan-desa-sadar-hukum',
            'konten' => '<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph;"><span style="font-size: 12.0pt; font-family: "Times New Roman",serif; mso-bidi-theme-font: minor-bidi;">Sosialisasi pembentukan dan pembinaan Desa Sadar Hukum di Desa Suka Maju menjadi langkah penting dalam membangun kesadaran dan pemahaman masyarakat terkait dengan hukum dan aturan yang berlaku. Melalui sosialisasi ini, warga desa diberikan pengetahuan tentang hak dan kewajiban mereka, serta pentingnya menjalankan kehidupan berdasarkan norma hukum yang berlaku. Dalam sosialisasi ini, warga desa diajak untuk memahami peraturan desa, peraturan pemerintah, dan undang-undang yang berlaku agar tercipta ketaatan hukum yang tinggi di Desa Suka Maju.</span></p>
            <p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph;"><span style="font-size: 12.0pt; font-family: "Times New Roman",serif; mso-bidi-theme-font: minor-bidi;">Selain itu, sosialisasi pembentukan dan pembinaan Desa Sadar Hukum juga bertujuan untuk memperkuat partisipasi masyarakat dalam pengambilan keputusan yang berhubungan dengan aspek hukum. Warga desa didorong untuk aktif terlibat dalam diskusi dan musyawarah terkait penyusunan peraturan desa, pembuatan kebijakan, serta penegakan hukum di tingkat desa. Hal ini memberikan kesempatan kepada warga desa untuk menyampaikan masukan dan pendapat mereka, sehingga tercipta peraturan desa yang berpihak kepada kepentingan masyarakat.</span></p>
            <p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph;"><span style="font-size: 12.0pt; font-family: "Times New Roman",serif; mso-bidi-theme-font: minor-bidi;">Selain memberikan pengetahuan dan meningkatkan partisipasi masyarakat, sosialisasi pembentukan dan pembinaan Desa Sadar Hukum juga berperan dalam meningkatkan kesadaran hukum dan mengurangi potensi pelanggaran hukum di Desa Suka Maju. Melalui sosialisasi ini, warga desa diberikan pemahaman tentang konsekuensi hukum dari tindakan-tindakan yang melanggar hukum. Masyarakat diajak untuk menghindari tindakan illegal, melakukan upaya pencegahan, dan menjaga keharmonisan serta keamanan di desa mereka.</span></p>',
            'excerpt' => 'Sosialisasi pembentukan dan pembinaan Desa Sadar Hukum di Desa Suka Maju menjadi langkah penting dalam membangun kesadaran dan pemahaman masyarakat terkait dengan hukum dan aturan yang berlaku. Melalu...',
            'gambar' => '2f21c_contohgambar2.jpeg',
            'tanggal_upload' => '2023-06-05 23:46:42',
        ]);

        Berita::create([
            'judul' => 'LOMBA VOLI ANTAR DUSUN',
            'slug' => 'lomba-voli-antar-dusun',
            'konten' => '<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph;"><span style="font-size: 12.0pt; font-family: "Times New Roman",serif;">Lomba voli antar dusun yang dilaksanakan di Desa Sukamaju adalah sebuah acara yang sangat dinantikan oleh seluruh warga desa. Lomba ini diadakan setiap tahun sebagai ajang untuk mempererat tali persaudaraan antar warga dusun dan juga untuk mempromosikan olahraga voli di masyarakat.&nbsp;</span></p>
            <p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph;"><span style="font-size: 12.0pt; font-family: "Times New Roman",serif;">Acara ini biasanya diikuti oleh masing-masing dusun di Desa Sukamaju dengan membentuk tim voli mereka sendiri. Setiap dusun akan mengirimkan tim terbaik mereka untuk berkompetisi dalam turnamen ini. Lomba voli ini tidak hanya melibatkan pemain dari kalangan muda, tetapi juga dari berbagai kelompok umur, termasuk pemain dewasa dan lansia. Ini mencerminkan semangat inklusivitas dan partisipasi aktif dari seluruh masyarakat desa.</span></p>
            <p><span style="font-size: 12.0pt; font-family: "Times New Roman",serif; mso-fareast-font-family: SimSun; mso-fareast-theme-font: minor-fareast; mso-ansi-language: EN-US; mso-fareast-language: ZH-CN; mso-bidi-language: AR-SA;">Selain sebagai ajang kompetisi, lomba voli antar dusun juga memberikan kesempatan bagi warga desa untuk saling bertukar pengalaman dan meningkatkan keterampilan dalam bermain voli. Selama persiapan lomba, para pemain sering melakukan latihan rutin dan belajar strategi permainan dari pelatih mereka. Ini juga menjadi waktu yang tepat untuk meningkatkan kebugaran fisik dan semangat juang dalam mencapai tujuan bersama.</span></p>
            <p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph;"><span style="font-size: 12.0pt; font-family: "Times New Roman",serif;">Selama lomba voli, suasana di Desa Sukamaju menjadi sangat meriah. Warga desa berkumpul di lapangan voli dengan antusiasme tinggi untuk mendukung tim mereka masing-masing. Selain itu, masyarakat dari dusun lain juga datang untuk memberikan dukungan dan semangat kepada tim-tim yang bertanding. Lomba ini juga menjadi kesempatan untuk membangun solidaritas dan persatuan antar dusun di Desa Sukamaju. Para pemain dan penonton saling bergembira dan menikmati momen kebersamaan ini sambil menikmati aksi-aksi seru di lapangan voli.</span></p>
            <p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph;"><span style="font-size: 12.0pt; font-family: "Times New Roman",serif;">Dengan adanya lomba voli antar dusun yang rutin diadakan di Desa Sukamaju, diharapkan dapat membangun semangat kebersamaan dan memperkuat persaudaraan antara warga desa. Selain itu, lomba ini juga menjadi sarana untuk meningkatkan kesehatan dan kebugaran fisik masyarakat melalui olahraga voli. Semoga kegiatan ini terus berlanjut dan memberikan manfaat positif bagi masyarakat Desa Sukamaju serta memperkuat ikatan antar warga dusun dalam menjaga keharmonisan desa.</span></p>',
            'excerpt' => 'Lomba voli antar dusun yang dilaksanakan di Desa Sukamaju adalah sebuah acara yang sangat dinantikan oleh seluruh warga desa. Lomba ini diadakan setiap tahun sebagai ajang untuk mempererat tali persau...',
            'gambar' => '3220e_gambar4.jpg',
            'tanggal_upload' => '2023-06-02 23:48:03',
        ]);

        Berita::create([
            'judul' => 'Rapat Penanganan Balita Stunting di Kantor Desa Sukamaju',
            'slug' => 'rapat-penanganan-balita-stunting-di-kantor-desa-sukamaju',
            'konten' => '<p class="MsoNormal" style="text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Pada tanggal 15 Mei 2023, Kantor Desa Suka Maju menyelenggarakan rapat penanganan balita stunting yang menjadi perhatian serius di desa tersebut. Rapat ini bertujuan untuk membahas strategi dan langkah konkret dalam menangani masalah stunting pada balita di Desa Suka Maju. Para pemangku kepentingan seperti petugas kesehatan, perwakilan lembaga sosial, dan para orang tua balita terlibat dalam rapat ini, menciptakan platform kolaboratif yang memungkinkan solusi efektif dalam menangani stunting di desa tersebut.</span></p>
            <p class="MsoNormal" style="text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Rapat penanganan balita stunting di Kantor Desa Suka Maju menjadi kesempatan untuk membahas penyebab dan dampak stunting serta upaya yang telah dilakukan untuk mengatasi masalah ini. Dalam rapat ini, petugas kesehatan memberikan presentasi dan informasi terkait gizi yang seimbang, pola makan yang benar, dan pentingnya perawatan kesehatan bagi balita. Orang tua balita juga berbagi pengalaman dan tantangan yang mereka hadapi dalam memberikan perhatian dan nutrisi yang memadai kepada anak-anak mereka.</span></p>
            <p class="MsoNormal" style="text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Selain itu, rapat ini juga menjadi forum untuk mengidentifikasi program-program dan kegiatan yang dapat dilakukan untuk mengurangi angka stunting di Desa Suka Maju. Perwakilan lembaga sosial dan masyarakat turut memberikan masukan dan usulan terkait program-program pendidikan, pemberdayaan ibu-ibu, dan peningkatan akses terhadap layanan kesehatan bagi balita. Diskusi yang berlangsung di rapat ini diharapkan dapat menghasilkan rencana aksi yang komprehensif dan terintegrasi untuk menangani stunting secara efektif.</span></p>
            <p class="MsoNormal" style="text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Melalui rapat penanganan balita stunting di Kantor Desa Suka Maju, tercipta kesadaran dan komitmen bersama untuk mengatasi masalah stunting dengan pendekatan yang holistik dan berkelanjutan. Rapat ini menjadi langkah awal dalam mengubah paradigma dan memberikan perhatian yang lebih serius terhadap kesehatan dan gizi balita di desa tersebut. Dengan melibatkan berbagai pihak terkait, diharapkan upaya penanganan stunting dapat dilakukan secara terkoordinasi dan berkesinambungan untuk mencapai hasil yang signifikan dalam meningkatkan kesehatan dan kualitas hidup balita di&nbsp;Desa&nbsp;Suka&nbsp;Maju.</span></p>',
            'excerpt' => 'Pada tanggal 15 Mei 2023, Kantor Desa Suka Maju menyelenggarakan rapat penanganan balita stunting yang menjadi perhatian serius di desa tersebut. Rapat ini bertujuan untuk membahas strategi dan langka...',
            'gambar' => '467bc_Picture3.jpg',
            'tanggal_upload' => '2023-06-01 23:52:55',
        ]);

        Berita::create([
            'judul' => 'Kegiatan Bulan Bahasa 2023',
            'slug' => 'kegiatan-bulan-bahasa-2023',
            'konten' => '<p class="MsoNormal" style="text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Kegiatan Bulan Bahasa 2023 di Desa Suka Maju menjadi momen yang sangat dinantikan oleh masyarakat desa. Bulan Bahasa merupakan waktu yang ditetapkan untuk memperingati pentingnya bahasa sebagai sarana komunikasi dan identitas budaya. Di Desa Suka Maju, kegiatan Bulan Bahasa diadakan dengan tujuan untuk meningkatkan kesadaran dan apresiasi terhadap kekayaan bahasa serta keberagaman budaya di desa tersebut.</span></p>
            <p class="MsoNormal" style="text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Selama Kegiatan Bulan Bahasa, berbagai kegiatan menarik dan edukatif diselenggarakan di Desa Suka Maju. Salah satunya adalah lomba membaca puisi dan cerita pendek dalam bahasa lokal. Lomba ini bertujuan untuk mendorong masyarakat desa untuk menghargai dan menggunakan bahasa lokal sebagai warisan budaya yang berharga. Selain itu, juga diadakan pameran karya sastra dan kesenian lokal, di mana warga desa dapat memamerkan hasil karya mereka yang terkait dengan bahasa dan budaya.</span></p>
            <p class="MsoNormal" style="text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Tak hanya itu, kegiatan Bulan Bahasa di Desa Suka Maju juga melibatkan kolaborasi antara generasi muda dan lansia dalam melestarikan bahasa dan budaya. Misalnya, diadakan lokakarya pembelajaran bahasa lokal bagi anak-anak dan remaja, yang dipimpin oleh para lansia yang memiliki keahlian dan pengetahuan mendalam tentang bahasa tersebut. Hal ini tidak hanya memfasilitasi transfer pengetahuan dari generasi tua ke generasi muda, tetapi juga membangun jembatan emosional dan menghargai peran penting lansia dalam menjaga dan merawat bahasa dan budaya di desa.</span></p>
            <p class="MsoNormal" style="text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Kegiatan Bulan Bahasa di Desa Suka Maju juga mencakup acara pertunjukan seni dan budaya yang melibatkan berbagai komunitas di desa tersebut. Pertunjukan ini menjadi wadah untuk memperlihatkan kekayaan seni dan budaya yang ada di Desa Suka Maju kepada masyarakat luas. Melalui kesenian tradisional seperti tarian, musik, dan teater, masyarakat desa dapat merasakan keindahan bahasa dan budaya mereka sendiri, serta memperkuat rasa bangga akan identitas budaya desa mereka.</span></p>
            <p><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif; mso-fareast-font-family: Calibri; mso-fareast-theme-font: minor-latin; mso-ansi-language: EN-ID; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">Dengan demikian, Kegiatan Bulan Bahasa 2023 di Desa Suka Maju bukan hanya menjadi ajang hiburan semata, tetapi juga menjadi momentum penting dalam mempromosikan dan memperkuat penggunaan bahasa lokal, melestarikan kebudayaan, serta meningkatkan kebanggaan masyarakat desa terhadap identitas&nbsp;budaya&nbsp;mereka.</span></p>',
            'excerpt' => 'Kegiatan Bulan Bahasa 2023 di Desa Suka Maju menjadi momen yang sangat dinantikan oleh masyarakat desa. Bulan Bahasa merupakan waktu yang ditetapkan untuk memperingati pentingnya bahasa sebagai sarana...',
            'gambar' => '4861f_Picture4.jpg',
            'tanggal_upload' => '2023-06-02 23:53:26',
        ]);

        Berita::create([
            'judul' => 'Inisiasi Pembentukan Forum Data sebagai penunjang Sistem Informasi Desa (SID)',
            'slug'  => 'inisiasi-pembentukan-forum-data-sebagai-penunjang-sistem-informasi-desa-sid',
            'konten' => '<p class="MsoListParagraphCxSpFirst" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Desa Suka Maju menginisiasi pembentukan Forum Data sebagai penunjang Sistem Informasi Desa (SID) yang ada. Forum Data ini bertujuan untuk meningkatkan kualitas dan aksesibilitas data desa serta memperkuat penggunaan SID dalam pengambilan keputusan yang berbasis data. Dalam Forum Data, terlibat berbagai pihak, seperti pemerintah desa, BPD (Badan Permusyawaratan Desa), tokoh masyarakat, dan perwakilan organisasi masyarakat lainnya.</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Pembentukan Forum Data diawali dengan identifikasi kebutuhan data desa yang relevan. Para anggota forum melakukan pemetaan data yang diperlukan untuk mengambil keputusan yang lebih baik dalam pengembangan desa. Data yang dibutuhkan dapat mencakup data demografis, ekonomi, infrastruktur, pendidikan, kesehatan, dan sektor lain yang relevan dengan kebutuhan pembangunan desa.</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">&nbsp;</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Selanjutnya, Forum Data bekerja sama dengan pihak terkait dalam mengumpulkan dan mengelola data yang dibutuhkan. Dalam hal ini, pemerintah desa dapat berperan sebagai penyedia data utama, sedangkan masyarakat dan organisasi lain dapat memberikan kontribusi data yang mereka miliki. Hal ini memungkinkan terciptanya sinergi dan kerja sama antara pemerintah desa dan masyarakat dalam pengumpulan dan pemutakhiran data desa secara berkala.</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">&nbsp;</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Forum Data juga berperan dalam mendukung pengembangan dan peningkatan kapasitas SID di Desa Suka Maju. Anggota forum dapat memberikan masukan dan saran terkait pengembangan sistem, pembaruan data, dan penggunaan SID secara efektif. Melalui kolaborasi ini, diharapkan SID dapat menjadi alat yang lebih efisien dan bermanfaat bagi pengelolaan data desa serta pengambilan keputusan yang berbasis data.</span></p>
            <p class="MsoListParagraphCxSpLast" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">&nbsp;</span></p>
            <p><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif; mso-fareast-font-family: Calibri; mso-fareast-theme-font: minor-latin; mso-ansi-language: EN-ID; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">Dengan pembentukan Forum Data sebagai penunjang SID, Desa Suka Maju menunjukkan komitmen dalam mengoptimalkan penggunaan data dalam pembangunan desa. Dengan data yang lengkap, akurat, dan terkelola dengan baik, diharapkan kebijakan dan program pembangunan desa dapat dirancang dan diimplementasikan dengan lebih tepat sasaran. Forum Data juga menjadi wadah partisipasi masyarakat dalam proses pengambilan keputusan yang lebih inklusif&nbsp;dan&nbsp;transparan.</span></p>',
            'excerpt' => 'Desa Suka Maju menginisiasi pembentukan Forum Data sebagai penunjang Sistem Informasi Desa (SID) yang ada. Forum Data ini bertujuan untuk meningkatkan kualitas dan aksesibilitas data desa serta memper...',
            'gambar' => '71190_Picture12.jpg',
            'tanggal_upload' => '2023-05-27 00:06:38',
        ]);

        Berita::create([
            'judul' => 'Sosialisasi dari BPJS Ketenagakerjaan Kabupaten',
            'slug'  => 'sosialisasi-dari-bpjs-ketenagakerjaan-kabupaten',
            'konten' => '<p class="MsoListParagraphCxSpFirst" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Pada tanggal 18 Mei 2023, Badan Penyelenggara Jaminan Sosial (BPJS) Ketenagakerjaan mengadakan kegiatan sosialisasi di Desa Sukamaju. Kegiatan ini bertujuan untuk memberikan pemahaman kepada warga desa tentang manfaat dan pentingnya memiliki jaminan sosial ketenagakerjaan. Selama kegiatan sosialisasi, BPJS Ketenagakerjaan menyampaikan informasi mengenai program-program yang mereka tawarkan kepada para pekerja, seperti program jaminan kecelakaan kerja, jaminan hari tua, dan jaminan kematian.</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">&nbsp;</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Dalam kegiatan sosialisasi tersebut, BPJS Ketenagakerjaan mengedukasi warga Desa Sukamaju tentang hak dan kewajiban mereka sebagai pekerja. Mereka menjelaskan bahwa setiap pekerja memiliki hak untuk mendapatkan jaminan sosial ketenagakerjaan dan wajib untuk membayar iuran bulanan sesuai dengan penghasilan yang diterima. BPJS Ketenagakerjaan juga memberikan contoh-contoh nyata mengenai manfaat jaminan sosial ketenagakerjaan, seperti perlindungan finansial saat mengalami kecelakaan kerja atau saat memasuki masa pensiun.</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">&nbsp;</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Selain memberikan informasi, BPJS Ketenagakerjaan juga memberikan kesempatan kepada warga Desa Sukamaju untuk bertanya dan berdiskusi seputar jaminan sosial ketenagakerjaan. Hal ini bertujuan untuk memperjelas pemahaman warga dan mengatasi berbagai kekhawatiran atau keraguan yang mungkin mereka miliki. Tim BPJS Ketenagakerjaan dengan sabar menjawab setiap pertanyaan warga dan memberikan solusi-solusi yang relevan.</span></p>
            <p class="MsoListParagraphCxSpLast" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">&nbsp;</span></p>
            <p><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif; mso-fareast-font-family: Calibri; mso-fareast-theme-font: minor-latin; mso-ansi-language: EN-ID; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">Kegiatan sosialisasi dari BPJS Ketenagakerjaan ini diharapkan dapat memberikan pemahaman yang lebih baik kepada warga Desa Sukamaju tentang pentingnya memiliki jaminan sosial ketenagakerjaan. Dengan pemahaman yang lebih baik, diharapkan warga desa akan lebih aktif dalam melindungi diri mereka sendiri dan keluarga mereka melalui program-program jaminan sosial ketenagakerjaan yang disediakan oleh BPJS Ketenagakerjaan. Semoga kegiatan ini dapat meningkatkan kesadaran masyarakat mengenai pentingnya perlindungan sosial dalam dunia kerja.</span></p>',
            'excerpt' => 'Pada tanggal 18 Mei 2023, Badan Penyelenggara Jaminan Sosial (BPJS) Ketenagakerjaan mengadakan kegiatan sosialisasi di Desa Sukamaju. Kegiatan ini bertujuan untuk memberikan pemahaman kepada warga des...',
            'gambar' => '72920_Picture13.jpg',
            'tanggal_upload' => '2023-06-07 00:04:41',
        ]);

        Berita::create([
            'judul' => 'Penyambutan dan Penerimaan Mahasiswa KKN (Kuliah kerja Nyata)  Universitas Sumatera Utara',
            'slug' => 'penyambutan-dan-penerimaan-mahasiswa-kkn-kuliah-kerja-nyata-universitas-sumatera-utara',
            'konten' => '<p class="MsoNormal" style="text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif; color: #333333; background: white;">Pada bulan Februari, Desa Suka Maju dengan antusias menyambut dan menerima mahasiswa KKN dari Universitas Sumatera Utara (USU). Penyambutan ini merupakan momen penting bagi desa, karena mahasiswa KKN akan menjadi mitra dalam pembangunan dan peningkatan kualitas hidup masyarakat setempat. Desa Suka Maju berkomitmen untuk memberikan dukungan dan kerjasama yang baik kepada mahasiswa KKN selama masa tugas mereka di desa.</span></p>
            <p class="MsoNormal" style="text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif; color: #333333; background: white;">Penyambutan dan penerimaan mahasiswa KKN di Desa Suka Maju dilakukan dengan acara formal yang melibatkan perwakilan desa, masyarakat, dan pihak universitas. Acara tersebut dimulai dengan sambutan dari kepala desa dan perwakilan universitas, yang memberikan penghargaan kepada mahasiswa atas komitmen mereka dalam menjalankan KKN di desa tersebut. Selanjutnya, mahasiswa diperkenalkan kepada masyarakat desa dan diberikan kesempatan untuk berinteraksi dan memahami kebutuhan serta harapan masyarakat terkait dengan KKN.</span></p>
            <p class="MsoNormal" style="text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif; color: #333333; background: white;">Selama masa penyambutan dan penerimaan, mahasiswa KKN juga diberikan orientasi khusus mengenai kondisi sosial, budaya, dan geografi Desa Suka Maju. Mereka dikenalkan dengan potensi dan tantangan yang ada di desa serta diberikan informasi tentang program-program pembangunan yang sedang berjalan. Selain itu, mahasiswa juga berkesempatan untuk melakukan kunjungan lapangan dan menjalin kontak awal dengan masyarakat setempat, guna memahami lebih dalam kebutuhan dan masalah yang perlu mereka fokuskan selama KKN.</span></p>
            <p class="MsoNormal" style="text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif; color: #333333; background: white;">&nbsp;</span></p>
            <p class="MsoNormal" style="text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif; color: #333333; background: white;">Selain acara resmi, penyambutan dan penerimaan mahasiswa KKN di Desa Suka Maju juga melibatkan kegiatan sosial dan budaya. Masyarakat desa menyelenggarakan acara seni dan budaya, seperti tarian, musik, dan pameran kerajinan lokal, sebagai bentuk apresiasi terhadap kedatangan mahasiswa KKN. Kegiatan ini tidak hanya memberikan hiburan, tetapi juga menjadi ajang untuk memperkenalkan kekayaan budaya desa kepada mahasiswa, sehingga terjalin hubungan yang harmonis antara mahasiswa KKN dan masyarakat setempat.</span></p>
            <p><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif; mso-fareast-font-family: Calibri; mso-fareast-theme-font: minor-latin; color: #333333; background: white; mso-ansi-language: EN-ID; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">Dengan demikian, penyambutan dan penerimaan mahasiswa KKN dari Universitas Sumatera Utara di Desa Suka Maju pada bulan Februari menjadi langkah awal yang penting dalam membangun sinergi antara mahasiswa dan masyarakat desa. Melalui kegiatan ini, tercipta kesadaran dan komitmen bersama untuk saling mendukung dan bekerja sama dalam mencapai tujuan pembangunan yang berkelanjutan. Mahasiswa KKN akan merasakan keramahan dan kebersamaan di Desa Suka Maju, sementara masyarakat setempat akan mendapatkan kontribusi berharga dari pengetahuan dan usaha mahasiswa dalam meningkatkan kualitas&nbsp;hidup&nbsp;mereka.</span></p>',
            'excerpt' => 'Pada bulan Februari, Desa Suka Maju dengan antusias menyambut dan menerima mahasiswa KKN dari Universitas Sumatera Utara (USU). Penyambutan ini merupakan momen penting bagi desa, karena mahasiswa KKN...',
            'gambar' => '4ae31_Picture5.jpg',
            'tanggal_upload' => '2023-05-23 00:06:38'
        ]);
        Berita::create([
            'judul' => 'Kegiatan Penggerakan Germas dan Edukasi Gizi Seimbang (makan buah dan sayur) dari Puskesmas.',
            'slug' => 'kegiatan-penggerakan-germas-dan-edukasi-gizi-seimbang-makan-buah-dan-sayur-dari-puskesmas',
            'konten' => '<p class="MsoNormal" style="text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Pada tanggal 5 Mei 2023, Puskesmas Desa Suka Maju menyelenggarakan kegiatan penggerakan Germas (Gerakan Masyarakat Hidup Sehat) dan edukasi gizi seimbang dengan fokus pada pentingnya mengonsumsi buah dan sayur. Kegiatan ini bertujuan untuk meningkatkan kesadaran masyarakat Desa Suka Maju akan pentingnya pola makan sehat dan gizi seimbang dalam menjaga kesehatan dan mencegah penyakit. </span></p>
            <p class="MsoNormal" style="text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Dalam kegiatan tersebut, Puskesmas Desa Suka Maju bekerja sama dengan tim kesehatan dan ahli gizi untuk memberikan edukasi kepada masyarakat tentang manfaat makan buah dan sayur, serta cara memasukkan mereka ke dalam pola makan sehari-hari. Melalui presentasi, diskusi, dan demo memasak, masyarakat diberikan pengetahuan dan keterampilan praktis untuk mengadopsi pola makan sehat dan mengonsumsi buah dan sayur secara rutin.</span></p>
            <p class="MsoNormal" style="text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Selain edukasi, kegiatan juga melibatkan penggerakan Germas, yang melibatkan partisipasi aktif masyarakat Desa Suka Maju. Puskesmas memfasilitasi aktivitas fisik seperti senam, jalan sehat, atau permainan tradisional yang melibatkan masyarakat dari berbagai usia. Gerakan ini bertujuan untuk meningkatkan aktivitas fisik sehari-hari dan mengajak masyarakat untuk menjalani gaya hidup yang lebih aktif dan sehat.</span></p>
            <p class="MsoNormal" style="text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Dalam kegiatan tersebut, Puskesmas Desa Suka Maju juga melibatkan pengenalan dan promosi produk lokal berupa buah dan sayur. Petani lokal diberikan kesempatan untuk memamerkan hasil panen mereka dan menjelaskan manfaat kesehatan dari produk-produk tersebut. Dengan cara ini, masyarakat dapat mendapatkan pemahaman yang lebih baik tentang pentingnya mendukung pertanian lokal dan mengonsumsi produk segar dari daerah mereka sendiri.</span></p>
            <p class="MsoNormal" style="text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Kegiatan penggerakan Germas dan edukasi gizi seimbang di Desa Suka Maju menjadi momentum penting dalam mengedukasi dan mendorong masyarakat untuk menjalani gaya hidup sehat. Dengan meningkatkan kesadaran akan pentingnya makan buah dan sayur serta melibatkan masyarakat secara aktif dalam aktivitas fisik, diharapkan terjadi perubahan positif dalam pola makan dan gaya hidup masyarakat. Puskesmas Desa Suka Maju berperan sebagai fasilitator dalam memberikan informasi, keterampilan, dan dukungan yang dibutuhkan oleh masyarakat untuk mencapai hidup sehat dan&nbsp;berkualitas.</span></p>',
            'excerpt' => 'Pada tanggal 5 Mei 2023, Puskesmas Desa Suka Maju menyelenggarakan kegiatan penggerakan Germas (Gerakan Masyarakat Hidup Sehat) dan edukasi gizi seimbang dengan fokus pada pentingnya mengonsumsi buah...',
            'gambar' => '6026d_Picture6.jpg',
            'tanggal_upload' => '2023-05-25 00:06:38'
        ]);
        Berita::create([
            'judul' => 'Bersih-Bersih di Kantor Desa dan Lapangan Desa',
            'slug' => 'bersih-bersih-di-kantor-desa-dan-lapangan-desa',
            'konten' => '<p class="MsoNormal" style="text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Pada tanggal 10 Mei 2023, Desa Suka Maju mengadakan pegelaran bersih-bersih di kantor desa dan lapangan desa. Kegiatan ini bertujuan untuk mewujudkan kebersihan dan kerapihan lingkungan di desa serta melibatkan partisipasi aktif masyarakat dalam menjaga kebersihan tempat umum. </span></p>
            <p class="MsoNormal" style="text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Dalam pegelaran bersih-bersih, warga desa, petugas kantor desa, dan pihak terkait bekerja sama untuk membersihkan dan merapikan area kantor desa dan lapangan desa. Mereka membersihkan sampah, menyapu, membersihkan jalan, serta melakukan pemangkasan dan penataan tanaman. Dalam prosesnya, masyarakat juga diajak untuk memilah dan membuang sampah sesuai dengan tempatnya, sehingga kesadaran akan pentingnya pembuangan sampah yang tepat juga ditanamkan.</span></p>
            <p class="MsoNormal" style="text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Selain itu, pegelaran bersih-bersih juga menjadi momen untuk meningkatkan kesadaran masyarakat tentang pentingnya menjaga kebersihan lingkungan. Pihak kantor desa memberikan penyuluhan dan edukasi kepada masyarakat mengenai dampak positif dari kebersihan lingkungan, baik dari segi kesehatan maupun estetika. Hal ini diharapkan dapat membentuk sikap dan kebiasaan yang berkelanjutan dalam menjaga kebersihan di desa.</span></p>
            <p class="MsoNormal" style="text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Selama pegelaran bersih-bersih, juga dilakukan kegiatan gotong royong untuk memperbaiki fasilitas umum yang ada di desa. Misalnya, perbaikan bangku, pengecatan pagar, atau perbaikan jalan kecil di sekitar lapangan desa. Dengan melibatkan partisipasi masyarakat, kegiatan ini bukan hanya menciptakan lingkungan yang bersih dan rapi, tetapi juga memperkuat ikatan sosial dan kebersamaan dalam masyarakat Desa Suka Maju.</span></p>
            <p><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif; mso-fareast-font-family: Calibri; mso-fareast-theme-font: minor-latin; mso-ansi-language: EN-ID; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">Pegelaran bersih-bersih di kantor desa dan lapangan desa Suka Maju pada tanggal 10 Mei 2023 merupakan upaya konkret untuk meningkatkan kebersihan dan keindahan desa secara keseluruhan. Melalui kegiatan ini, diharapkan masyarakat dapat memahami pentingnya menjaga kebersihan dan kerapihan sebagai bentuk partisipasi aktif dalam pembangunan desa. Selain itu, pegelaran bersih-bersih juga menjadi sarana untuk mempererat hubungan sosial dan meningkatkan kebersamaan di antara&nbsp;warga&nbsp;desa.</span></p>',
            'excerpt' => 'Pada tanggal 10 Mei 2023, Desa Suka Maju mengadakan pegelaran bersih-bersih di kantor desa dan lapangan desa. Kegiatan ini bertujuan untuk mewujudkan kebersihan dan kerapihan lingkungan di desa serta...',
            'gambar' => '61e65_Picture7.jpg',
            'tanggal_upload' => '2023-05-26 12:06:38'
        ]);
        Berita::create([
            'judul' => 'Rapat Pembahasan dan Penetapan RKPDes tahun 2023',
            'slug' => 'rapat-pembahasan-dan-penetapan-rkpdes-tahun-2023',
            'konten' => '<p class="MsoListParagraphCxSpFirst" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Pada bulan Januari, Desa Suka Maju mengadakan rapat pembahasan dan penetapan RKPDes (Rencana Kerja Pemerintah Desa) tahun 2023. Rapat ini merupakan momen penting dalam merumuskan program kerja dan anggaran desa untuk tahun yang akan datang. Partisipasi aktif dari semua pihak terlibat, seperti perwakilan masyarakat, kepala desa, serta unsur pemerintahan desa, sangat diperlukan dalam rapat ini.</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">&nbsp;</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Rapat pembahasan RKPDes bertujuan untuk mengidentifikasi kebutuhan dan aspirasi masyarakat Desa Suka Maju serta merencanakan program kerja yang akan dilaksanakan oleh pemerintah desa dalam tahun tersebut. Dalam rapat ini, disampaikan berbagai masukan dan usulan dari masyarakat mengenai isu-isu penting seperti infrastruktur, pendidikan, kesehatan, pertanian, dan lainnya. Diskusi dan perdebatan yang konstruktif dilakukan untuk mencapai kesepakatan bersama mengenai prioritas program kerja desa.</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">&nbsp;</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Setelah melalui tahap pembahasan, rapat kemudian dilanjutkan dengan penetapan RKPDes. Pemerintah desa dan pihak terkait melakukan evaluasi terhadap usulan dan saran yang telah disampaikan oleh masyarakat. Berdasarkan pertimbangan tersebut, program kerja yang paling relevan dan memprioritaskan kebutuhan masyarakat dipilih dan diintegrasikan ke dalam RKPDes tahun 2023. RKPDes yang telah ditetapkan menjadi acuan dalam perencanaan dan pelaksanaan kegiatan desa selama setahun ke depan.</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">&nbsp;</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Selama rapat pembahasan dan penetapan RKPDes, juga dilakukan komunikasi dan sosialisasi kepada masyarakat mengenai isi dan prioritas RKPDes tahun 2023. Hal ini dilakukan untuk memastikan transparansi dan partisipasi masyarakat dalam proses perencanaan dan pelaksanaan program kerja desa. Dengan demikian, masyarakat dapat terlibat aktif dalam pengawasan dan evaluasi terhadap pelaksanaan RKPDes, sehingga tercipta akuntabilitas dan efektivitas dalam pemerintahan desa.</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">&nbsp;</span></p>
            <p class="MsoListParagraphCxSpLast" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Rapat pembahasan dan penetapan RKPDes tahun 2023 pada bulan Januari menjadi tonggak awal dalam perencanaan dan pelaksanaan program kerja desa. Melalui rapat ini, pemerintah desa dan masyarakat Desa Suka Maju berkolaborasi dalam menentukan prioritas dan langkah-langkah konkret untuk meningkatkan kesejahteraan dan pembangunan desa. Keputusan yang dihasilkan dari rapat ini menjadi dasar bagi pemerintah desa dalam mengalokasikan sumber daya dan mengimplementasikan program kerja yang relevan dan sesuai dengan kebutuhan&nbsp;masyarakat.</span></p>',
            'excerpt' => 'Pada bulan Januari, Desa Suka Maju mengadakan rapat pembahasan dan penetapan RKPDes (Rencana Kerja Pemerintah Desa) tahun 2023. Rapat ini merupakan momen penting dalam merumuskan program kerja dan ang...',
            'gambar' => '68e6f_Picture8.jpg',
            'tanggal_upload' => '2023-05-23 10:06:38'
        ]);
        Berita::create([
            'judul' => 'Monitoring Kegiatan APBDesa Tahun Anggaran 2023',
            'slug' => 'monitoring-kegiatan-apbdesa-tahun-anggaran-2023',
            'konten' => '<p class="MsoListParagraphCxSpFirst" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Pada tahun 2023, Desa Suka Maju melaksanakan monitoring kegiatan APBDesa (Anggaran Pendapatan dan Belanja Desa) sebagai bagian dari upaya untuk memastikan transparansi dan akuntabilitas pengelolaan anggaran desa. Monitoring dilakukan untuk memastikan bahwa dana yang dialokasikan sesuai dengan rencana dan tujuan yang telah ditetapkan dalam APBDesa.</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">&nbsp;</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Tim monitoring yang terdiri dari pihak pemerintah desa, BPD (Badan Permusyawaratan Desa), dan masyarakat, bekerja sama dalam melaksanakan monitoring kegiatan APBDesa. Mereka melakukan kunjungan lapangan ke lokasi kegiatan yang telah direncanakan dan mengumpulkan informasi terkait kemajuan pelaksanaan kegiatan tersebut. Selain itu, tim juga memeriksa dokumen dan laporan yang berkaitan dengan penggunaan anggaran desa.</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">&nbsp;</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Selama proses monitoring, tim juga melibatkan partisipasi aktif masyarakat. Masyarakat diberikan kesempatan untuk memberikan masukan, pendapat, dan evaluasi terhadap pelaksanaan kegiatan yang didanai oleh APBDesa. Hal ini bertujuan untuk memastikan bahwa kegiatan tersebut benar-benar bermanfaat dan sesuai dengan kebutuhan masyarakat. Melalui partisipasi masyarakat dalam monitoring, diharapkan akan tercipta kontrol sosial yang efektif dalam pengelolaan anggaran desa.</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">&nbsp;</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Hasil dari monitoring kegiatan APBDesa akan dikomunikasikan kepada masyarakat dalam bentuk laporan atau informasi publik. Laporan tersebut memuat informasi mengenai realisasi anggaran, progress pelaksanaan kegiatan, serta evaluasi terhadap hasil yang telah dicapai. Dengan adanya transparansi informasi ini, masyarakat dapat memahami dan mengawasi penggunaan anggaran desa secara lebih baik.</span></p>
            <p class="MsoListParagraphCxSpLast" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">&nbsp;</span></p>
            <p><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif; mso-fareast-font-family: Calibri; mso-fareast-theme-font: minor-latin; mso-ansi-language: EN-ID; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">Dengan adanya monitoring kegiatan APBDesa tahun 2023, Desa Suka Maju menunjukkan komitmen dalam pengelolaan anggaran desa yang transparan dan akuntabel. Melalui kegiatan ini, pemerintah desa dan masyarakat berkolaborasi dalam mengawasi dan mengevaluasi pelaksanaan kegiatan yang didanai oleh APBDesa. Dengan pengawasan yang baik, diharapkan penggunaan anggaran desa dapat lebih efisien dan efektif, serta memberikan dampak positif yang nyata bagi masyarakat&nbsp;Desa&nbsp;Suka&nbsp;Maju.</span></p>',
            'excerpt' => 'Pada tahun 2023, Desa Suka Maju melaksanakan monitoring kegiatan APBDesa (Anggaran Pendapatan dan Belanja Desa) sebagai bagian dari upaya untuk memastikan transparansi dan akuntabilitas pengelolaan an...',
            'gambar' => '6ac25_Picture9.jpg',
            'tanggal_upload' => '2023-05-22 10:06:38'
        ]);
        Berita::create([
            'judul' => 'Penanaman Pohon  Cempaka dalam Peringatan Hari Lingkungan Hidup',
            'slug' => 'penanaman-pohon-cempaka-dalam-peringatan-hari-lingkungan-hidup',
            'konten' => '<p class="MsoListParagraphCxSpFirst" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Pada bulan April 2023, Desa Suka Maju melaksanakan kegiatan penanaman pohon cempaka dalam peringatan Hari Lingkungan Hidup. Kegiatan ini merupakan bagian dari upaya desa untuk meningkatkan kesadaran akan pentingnya menjaga dan melestarikan lingkungan alam sekitar. Pohon cempaka dipilih karena memiliki nilai estetika yang tinggi dan memberikan manfaat ekologis bagi lingkungan.</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">&nbsp;</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Dalam peringatan Hari Lingkungan Hidup, masyarakat Desa Suka Maju, pemerintah desa, serta siswa-siswa sekolah setempat bergabung dalam kegiatan penanaman pohon cempaka. Lokasi penanaman ditentukan dengan memperhatikan aspek kebutuhan lingkungan, seperti pemilihan tempat yang strategis untuk memperindah kawasan desa dan memberikan perlindungan bagi lingkungan hidup.</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">&nbsp;</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Selama kegiatan penanaman pohon cempaka, juga dilakukan edukasi kepada masyarakat tentang pentingnya menjaga dan merawat lingkungan. Dalam kegiatan ini, diberikan informasi mengenai manfaat dari pohon cempaka, seperti memberikan oksigen, meredam polusi udara, dan menyediakan habitat bagi berbagai jenis fauna. Selain itu, pentingnya menjaga kelestarian alam dan peran setiap individu dalam menjaga kelestarian lingkungan juga disampaikan kepada masyarakat.</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">&nbsp;</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Setelah penanaman dilakukan, pemerintah desa dan masyarakat Desa Suka Maju akan berkolaborasi dalam merawat pohon cempaka yang ditanam. Perawatan meliputi penyiraman, pemupukan, serta pemantauan pertumbuhan pohon. Melalui perawatan ini, diharapkan pohon cempaka dapat tumbuh subur dan memberikan manfaat bagi lingkungan desa.</span></p>
            <p class="MsoListParagraphCxSpLast" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">&nbsp;</span></p>
            <p><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif; mso-fareast-font-family: Calibri; mso-fareast-theme-font: minor-latin; mso-ansi-language: EN-ID; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">Kegiatan penanaman pohon cempaka dalam peringatan Hari Lingkungan Hidup di Desa Suka Maju merupakan upaya konkret dalam menjaga kelestarian lingkungan dan memperindah desa. Melalui kegiatan ini, diharapkan kesadaran masyarakat tentang pentingnya menjaga lingkungan semakin meningkat dan terbentuknya komitmen bersama dalam menjaga kelestarian alam. Selain itu, kegiatan penanaman pohon juga memiliki dampak positif jangka panjang dalam mengurangi dampak perubahan iklim dan meningkatkan kualitas hidup&nbsp;masyarakat.</span></p>',
            'excerpt' => 'Pada bulan April 2023, Desa Suka Maju melaksanakan kegiatan penanaman pohon cempaka dalam peringatan Hari Lingkungan Hidup. Kegiatan ini merupakan bagian dari upaya desa untuk meningkatkan kesadaran a...',
            'gambar' => '6dccf_Picture10.jpg',
            'tanggal_upload' => '2023-05-27 20:06:38'
        ]);
        Berita::create([
            'judul' => 'Bulan Bung Karno',
            'slug' => 'bulan-bung-karno',
            'konten' => '<p class="MsoListParagraphCxSpFirst" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Pada tanggal 6 Juni 2023, Desa Suka Maju merayakan peringatan Bulan Bung Karno sebagai bentuk penghormatan dan penghargaan terhadap jasa-jasa dan warisan pemikiran dari Bapak Proklamator, Ir. Soekarno. Peringatan ini merupakan momen penting untuk mengenang perjuangan Soekarno dalam memimpin pergerakan nasional menuju kemerdekaan Indonesia.</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">&nbsp;</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Dalam rangka peringatan Bulan Bung Karno, Desa Suka Maju mengadakan sejumlah kegiatan yang mencerminkan semangat dan nilai-nilai yang ditanamkan oleh Soekarno. Kegiatan ini meliputi upacara bendera, diskusi, seminar, pameran foto dan dokumentasi sejarah, serta pertunjukan seni dan budaya. Melalui kegiatan ini, masyarakat Desa Suka Maju dapat menghargai peran penting Soekarno dalam perjuangan kemerdekaan dan pembangunan nasional.</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">&nbsp;</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Selama peringatan Bulan Bung Karno, juga dilakukan kegiatan edukasi dan sosialisasi mengenai pemikiran dan nilai-nilai yang diwariskan oleh Soekarno. Pemerintah desa dapat mengundang narasumber yang kompeten untuk memberikan ceramah, seminar, atau lokakarya yang membahas pemikiran-pemikiran besar dari Soekarno seperti Pancasila, kepemimpinan, nasionalisme, dan demokrasi. Melalui kegiatan ini, diharapkan masyarakat Desa Suka Maju dapat memperdalam pemahaman mereka tentang pemikiran Soekarno dan menerapkan nilai-nilai tersebut dalam kehidupan sehari-hari.</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">&nbsp;</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Selain itu, peringatan Bulan Bung Karno di Desa Suka Maju juga menjadi momen untuk meningkatkan kesadaran dan partisipasi masyarakat dalam memperkuat persatuan dan kesatuan sebagai bangsa Indonesia. Melalui kegiatan seperti lomba pidato, puisi, atau penulisan esai mengenai perjuangan Soekarno dan semangat nasionalisme, masyarakat dapat menggali dan mengekspresikan rasa cinta dan bangga terhadap tanah air serta semangat untuk berkontribusi dalam pembangunan desa dan negara.</span></p>
            <p class="MsoListParagraphCxSpMiddle" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">&nbsp;</span></p>
            <p class="MsoListParagraphCxSpLast" style="margin-left: 22.5pt; mso-add-space: auto; text-align: justify;"><span lang="EN-ID" style="font-size: 12.0pt; line-height: 107%; font-family: "Times New Roman",serif;">Peringatan Bulan Bung Karno di Desa Suka Maju pada tanggal 6 Juni 2023 merupakan bentuk penghargaan dan penghormatan terhadap jasa dan pemikiran Soekarno sebagai tokoh penting dalam sejarah bangsa Indonesia. Melalui berbagai kegiatan yang melibatkan masyarakat, pemerintah desa, dan elemen-elemen masyarakat lainnya, diharapkan semangat perjuangan dan pemikiran Soekarno dapat terus dikenang dan menjadi inspirasi bagi generasi muda dalam membangun masa depan yang&nbsp;lebih&nbsp;baik.</span></p>',
            'excerpt' => 'Pada tanggal 6 Juni 2023, Desa Suka Maju merayakan peringatan Bulan Bung Karno sebagai bentuk penghormatan dan penghargaan terhadap jasa-jasa dan warisan pemikiran dari Bapak Proklamator, Ir. Soekarno...',
            'gambar' => '6f934_Picture11.jpg',
            'tanggal_upload' => '2023-05-22 04:06:38'
        ]);

    }
}